/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author aleja
 */
public class Principal extends javax.swing.JFrame implements ActionListener{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * Creates new form Principal
     */
    public Principal() {
        
        initComponents();
        
        setResizable(false);
        
        fondo.setIcon(new ImageIcon("./src/main/java/imagenes/fondoYLogoAguatal.jpg"));
        
        setTitle("AGUATAL CORPORATION");
        
        
        //añadimos el actionlistener a los botones y textArea que van a realizar cosas
        botonInicioSesion.addActionListener((ActionListener) this);//iniciosesion
        botonRegistrarse.addActionListener((ActionListener) this);//registro
        modoAdmin.addActionListener((ActionListener) this);//vista
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        modoAdmin = new javax.swing.JButton();
        panelCentralInicio = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaUsuario = new javax.swing.JTextArea();
        textUsuario = new javax.swing.JTextField();
        textPass = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        botonInicioSesion = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        botonRegistrarse = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modoAdmin.setText("Acceder modo administrador");
        panelFondo.add(modoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, -1));

        panelCentralInicio.setBackground(new java.awt.Color(204, 255, 255));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        areaUsuario.setColumns(20);
        areaUsuario.setRows(4);
        areaUsuario.setToolTipText("nombre de usuario");
        jScrollPane1.setViewportView(areaUsuario);

        textUsuario.setEditable(false);
        textUsuario.setBackground(new java.awt.Color(204, 255, 255));
        textUsuario.setForeground(new java.awt.Color(0, 0, 0));
        textUsuario.setText(" Usuario:");
        textUsuario.setBorder(null);

        textPass.setEditable(false);
        textPass.setBackground(new java.awt.Color(204, 255, 255));
        textPass.setForeground(new java.awt.Color(0, 0, 0));
        textPass.setText("Password:");
        textPass.setBorder(null);

        jTextField1.setEditable(false);
        jTextField1.setText(" INICIO");

        botonInicioSesion.setText("Iniciar sesion");

        jTextField2.setEditable(false);
        jTextField2.setText("Aun no estas registrado?");

        botonRegistrarse.setText("Registrasrse");

        javax.swing.GroupLayout panelCentralInicioLayout = new javax.swing.GroupLayout(panelCentralInicio);
        panelCentralInicioLayout.setHorizontalGroup(
        	panelCentralInicioLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(panelCentralInicioLayout.createSequentialGroup()
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGroup(panelCentralInicioLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(panelCentralInicioLayout.createSequentialGroup()
        					.addComponent(botonInicioSesion)
        					.addGap(169))
        				.addGroup(panelCentralInicioLayout.createSequentialGroup()
        					.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(botonRegistrarse)
        					.addGap(107))))
        		.addGroup(panelCentralInicioLayout.createSequentialGroup()
        			.addGap(72)
        			.addGroup(panelCentralInicioLayout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(textPass, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(panelCentralInicioLayout.createSequentialGroup()
        					.addComponent(textUsuario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(0)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(panelCentralInicioLayout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        				.addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
        			.addGap(0, 176, Short.MAX_VALUE))
        		.addGroup(Alignment.LEADING, panelCentralInicioLayout.createSequentialGroup()
        			.addGap(133)
        			.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(236, Short.MAX_VALUE))
        );
        panelCentralInicioLayout.setVerticalGroup(
        	panelCentralInicioLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panelCentralInicioLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        			.addGap(12)
        			.addGroup(panelCentralInicioLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        				.addComponent(textUsuario, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(panelCentralInicioLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textPass, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(botonInicioSesion)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(panelCentralInicioLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(botonRegistrarse)
        				.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(21, Short.MAX_VALUE))
        );
        panelCentralInicio.setLayout(panelCentralInicioLayout);

        panelFondo.add(panelCentralInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 280, 210));
        panelFondo.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(panelFondo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(panelFondo, GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaUsuario;
    private javax.swing.JButton botonInicioSesion;
    private javax.swing.JButton botonRegistrarse;
    private javax.swing.JLabel fondo;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton modoAdmin;
    private javax.swing.JPanel panelCentralInicio;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JTextField textPass;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        
        Object objeto = e.getSource();//recogemos tipo de objeto de e
        
        if (objeto instanceof JButton) {
            
            JButton boton = (JButton) objeto;//casting a boton
            
            switch(boton.getText()){
                
                case "Acceder modo administrador":
                    InicioAdmin admin = new InicioAdmin();
                    setVisible(false);//deshabitamos vista de inicio sesion
                    admin.setVisible(true);//mostramos el inicio de admin
                    break;
                    
                case "Registrasrse":
                    
                    Registro vistaRegistro = new Registro();
                    setVisible(false);//deshabitamos vista de inicio sesion
                     vistaRegistro.setVisible(true);//mostramos el registro
                    break;
                    
                case "Iniciar sesion":
                    break;
            }
        }
    }

}